/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.basico;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuarios;
import vista.admin.AdminForm;
import vista.auth.Login;

/**
 *
 * @author Manolo
 */
public class VistaUsuarioBasicoForm extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarioBasicoForm
     */
    
    Usuarios user;
    
    public VistaUsuarioBasicoForm() {
        initComponents();
        jMenuMiPerfil.setVisible(false);
        jMenuSalir.setVisible(false);
        jMenuControlador.setVisible(false);
        ponLaAyuda();
    }
   
    public VistaUsuarioBasicoForm(Usuarios usuario) {
        initComponents();
        this.user = usuario;
        jMenuLoginRegistro.setVisible(false);
        if ("administrador".equals(user.getRol())){
            jMenuControlador.setVisible(true);
        }else{
            jMenuControlador.setVisible(false);
        }
        this.setTitle("Padel Land - Vista de usuario | Logged ["+user.getEmail()+"]");
        ponLaAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVerPistas = new javax.swing.JMenu();
        jMenuReservar = new javax.swing.JMenu();
        jMenuContacto = new javax.swing.JMenu();
        jMenuMiPerfil = new javax.swing.JMenu();
        jMenuControlador = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();
        jMenuLoginRegistro = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemVerAyuda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padel Land - Vista de usuario | Desconectado");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/vistaUsuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuVerPistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icono-pistas-menubar.png"))); // NOI18N
        jMenuVerPistas.setText("Ver Pistas");
        jMenuVerPistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVerPistasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVerPistas);

        jMenuReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icono-reserva-menubar.png"))); // NOI18N
        jMenuReservar.setText("Reservar");
        jMenuReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuReservarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuReservar);

        jMenuContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icons8-correo-electrónico-100.png"))); // NOI18N
        jMenuContacto.setText("Contacto");
        jMenuContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuContactoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuContacto);

        jMenuMiPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icons8-configuración-del-administrador-40.png"))); // NOI18N
        jMenuMiPerfil.setText("Ver Perfil");
        jMenuMiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMiPerfilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuMiPerfil);

        jMenuControlador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icons8-moderador-masculino-48.png"))); // NOI18N
        jMenuControlador.setText("Control");
        jMenuControlador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuControladorMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuControlador);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icono-salir.png"))); // NOI18N
        jMenuSalir.setText("Desconectar");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        jMenuLoginRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icons8-accede-redondeado-derecho-100.png"))); // NOI18N
        jMenuLoginRegistro.setText("Login/Registro");
        jMenuLoginRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLoginRegistroMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLoginRegistro);

        jMenuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/icons8-información-40.png"))); // NOI18N
        jMenuInfo.setText("Información");

        jMenuItemVerAyuda.setText("Ayuda");
        jMenuInfo.add(jMenuItemVerAyuda);

        jMenuItem2.setText("Acerca de ...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuInfo.add(jMenuItem2);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que quieres salir? ", "Confirmación de cierre de ventana",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            user = null;
            jMenuMiPerfil.setVisible(false);
            jMenuSalir.setVisible(false);
            jMenuControlador.setVisible(false);
            jMenuLoginRegistro.setVisible(true);
            this.setTitle("Padel Land - Vista de usuario | Desconectado");

        }
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuMiPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMiPerfilMouseClicked
        // TODO add your handling code here:
        MiPerfilForm form = new MiPerfilForm(user);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuMiPerfilMouseClicked

    private void jMenuVerPistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVerPistasMouseClicked
        // TODO add your handling code here:
        VerPistasForm form = new VerPistasForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuVerPistasMouseClicked

    private void jMenuReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuReservarMouseClicked
        // TODO add your handling code here:
        ReservaForm form = new ReservaForm(user);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuReservarMouseClicked

    private void jMenuContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuContactoMouseClicked
        // TODO add your handling code here:
        Contacto form = new Contacto(user);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuContactoMouseClicked

    private void jMenuLoginRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLoginRegistroMouseClicked
        // TODO add your handling code here:
        Login form = new Login(this);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuLoginRegistroMouseClicked

    private void jMenuControladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuControladorMouseClicked
        // TODO add your handling code here:
        AdminForm vistaAdmin = new AdminForm(user);
        vistaAdmin.pack();
        vistaAdmin.setLocationRelativeTo(null);
        vistaAdmin.setVisible(true);
        AdminForm.jLabelBienvenida.setText("<html><body>¡Bienvenido "+user.getNombreCompleto()+"!<br>Esta es la vista de Administrador de Padel Land</body></html>");
        vistaAdmin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuControladorMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AboutMe dialog = new AboutMe(this, false);
        dialog.setVisible(true);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void ponLaAyuda(){
        try{
            //Carga el fichero de ayuda
            File fichero = new File("src/help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            //Carga el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(null,hsURL);
            HelpBroker hb = helpset.createHelpBroker();
            
            //Ponemos la ayuda
            getRootPane().requestFocus();
            hb.enableHelpKey(getRootPane(), "principal", helpset);
            hb.enableHelpOnButton(jMenuItemVerAyuda, "principal", helpset);
        }catch(IllegalArgumentException | MalformedURLException | HelpSetException ex){
            Logger.getLogger(VistaUsuarioBasicoForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioBasicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioBasicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioBasicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioBasicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuarioBasicoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContacto;
    private javax.swing.JMenu jMenuControlador;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemVerAyuda;
    private javax.swing.JMenu jMenuLoginRegistro;
    private javax.swing.JMenu jMenuMiPerfil;
    private javax.swing.JMenu jMenuReservar;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuVerPistas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
