package modelo;
// Generated 12-feb-2022 12:26:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DiasNoDisponibles generated by hbm2java
 */
public class DiasNoDisponibles  implements java.io.Serializable {


     private long id;
     private Date dia;

    public DiasNoDisponibles() {
    }

    public DiasNoDisponibles(long id, Date dia) {
       this.id = id;
       this.dia = dia;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }




}


