package modelo;
// Generated 12-feb-2022 12:26:16 by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Pistas generated by hbm2java
 */
public class Pistas  implements java.io.Serializable {


     private long id;
     private String nombrePista;
     private Blob imagenPista;
     private Set reservases = new HashSet(0);

    public Pistas() {
    }

	
    public Pistas(String nombrePista, Blob imagenPista) {
        this.nombrePista = nombrePista;
        this.imagenPista = imagenPista;
    }
    public Pistas(String nombrePista, Blob imagenPista, Set reservases) {
       this.nombrePista = nombrePista;
       this.imagenPista = imagenPista;
       this.reservases = reservases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public String getNombrePista() {
        return this.nombrePista;
    }
    
    public void setNombrePista(String nombrePista) {
        this.nombrePista = nombrePista;
    }
    
    public Blob getImagenPista() {
        return this.imagenPista;
    }
    
    public void setImagenPista(Blob imagenPista){
        this.imagenPista = imagenPista;
    }
    
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }
}


